### ISSUE TITLE
SSR breaks with React Router v4

### ISSUE THREAD

**Issue by stnwk** [apollostack/apollo#68]
When using Apollo's SSR implementation with react-router v4 with the following code (in express-context, assuming `res` was provided bei `express`) the following error appears:

```js
    const context = createServerRenderContext();
    const client = new ApolloClient({
      ssrMode: true,
      networkInterface: createNetworkInterface('http://localhost:3000/graphql', {
        credentials: 'same-origin',
        headers: req.headers,
      }),
    });

    const app = (<ApolloProvider client={client}>
      <ServerRouter
        location={req.url}
        context={context}
      >
        <div>
          <h1>Hello World!</h1>

          <Match pattern="/" exactly render={() => (<span>Home</span>)} />
          <Match pattern="/foo" render={() => (<span>Foo</span>)} />
          <Match pattern="/bar" render={() => (<span>Bar</span>)} />
          <Miss render={() => (<span>Sorry, nothing found =(</span>)} />
        </div>
      </ServerRouter>
    </ApolloProvider>);

    getDataFromTree(data.children).then((apolloContext: Object) => {
      // this breaks...
    }).catch((e: Object) => {
      throw new Error(e);
    });
```

Error Message:
```
TypeError: Cannot set property 'hasMissComponent' of undefined
    at Object.registerMissPresence (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:109436:45)
    at new Miss (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:107196:30)
    at getQueriesFromTree (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:70527:27)
    at /Users/Stefan/Documents/www/projects/starterkit/build/server.js:70543:78
    at forEachSingleChild (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:66125:10)
    at traverseAllChildrenImpl (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:67110:7)
    at traverseAllChildrenImpl (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:67126:25)
    at traverseAllChildren (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:67205:12)
    at Object.forEachChildren [as forEach] (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:66145:5)
    at getQueriesFromTree (/Users/Stefan/Documents/www/projects/starterkit/build/server.js:70543:28)
```

Any idea on how to setup react-router v4 with apollo?

**Comment by stubailo** [comment]
Can you open this issue on react-apollo please?

**Comment by stnwk** [comment]
Done, sorry. Messed up the tabs when creating the issue.
Moved to: https://github.com/apollostack/react-apollo/issues/215
